version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Nancy.Metadata.OpenApi/Nancy.Metadata.OpenApi.csproj
build_script:
  - cmd: dotnet publish ./Nancy.Metadata.OpenApi/Nancy.Metadata.OpenApi.csproj -c release -v minimal
artifacts:
  - path: '**\*.nupkg'
